"""
YOLO label emission, dataset.yaml, and per-sample manifests.

Converts annotation polygons -> axis-aligned boxes -> normalized YOLO lines
(`class_id xc yc w h`), clipping to the image and dropping boxes that fall
mostly out of frame or are too small to train on (config.MIN_BOX_SIDE_NORM).
"""
from __future__ import annotations

import json
from dataclasses import dataclass

from .config import CLASS_NAMES, CLASS_VERSION, MIN_BOX_SIDE_NORM
from .core import Sample


@dataclass
class YoloBox:
    class_id: int
    xc: float
    yc: float
    w: float
    h: float

    def line(self) -> str:
        return f"{self.class_id} {self.xc:.6f} {self.yc:.6f} {self.w:.6f} {self.h:.6f}"


def _polygon_area(poly: list[tuple[float, float]]) -> float:
    """Absolute shoelace area of a polygon (>=0)."""
    n = len(poly)
    if n < 3:
        return 0.0
    s = 0.0
    for i in range(n):
        x0, y0 = poly[i]
        x1, y1 = poly[(i + 1) % n]
        s += x0 * y1 - x1 * y0
    return abs(s) * 0.5


def clip_polygon_to_rect(
    poly: list[tuple[float, float]], W: float, H: float
) -> list[tuple[float, float]]:
    """Sutherland-Hodgman clip of `poly` against the frame [0,W] x [0,H].

    Returns the (possibly empty) clipped polygon. Pure-python, no deps.
    """
    def clip_edge(
        subject: list[tuple[float, float]],
        inside,
        intersect,
    ) -> list[tuple[float, float]]:
        if not subject:
            return []
        out: list[tuple[float, float]] = []
        prev = subject[-1]
        prev_in = inside(prev)
        for cur in subject:
            cur_in = inside(cur)
            if cur_in:
                if not prev_in:
                    out.append(intersect(prev, cur))
                out.append(cur)
            elif prev_in:
                out.append(intersect(prev, cur))
            prev, prev_in = cur, cur_in
        return out

    def inter(p, q, t):  # linear interp p->q
        return (p[0] + (q[0] - p[0]) * t, p[1] + (q[1] - p[1]) * t)

    pts = list(poly)
    # left x >= 0
    pts = clip_edge(pts, lambda p: p[0] >= 0.0,
                    lambda p, q: inter(p, q, (0.0 - p[0]) / (q[0] - p[0])))
    # right x <= W
    pts = clip_edge(pts, lambda p: p[0] <= W,
                    lambda p, q: inter(p, q, (W - p[0]) / (q[0] - p[0])))
    # top y >= 0
    pts = clip_edge(pts, lambda p: p[1] >= 0.0,
                    lambda p, q: inter(p, q, (0.0 - p[1]) / (q[1] - p[1])))
    # bottom y <= H
    pts = clip_edge(pts, lambda p: p[1] <= H,
                    lambda p, q: inter(p, q, (H - p[1]) / (q[1] - p[1])))
    return pts


def sample_to_yolo(sample: Sample, *, min_visible: float = 0.35) -> list[YoloBox]:
    """Convert a sample's annotations to clipped, normalized YOLO boxes.

    Visibility is measured on the TRUE polygon (correct for rotated/perspective-
    warped boxes, unlike an axis-aligned-box area ratio): we clip the annotation
    polygon to the frame (Sutherland-Hodgman) and keep it only if the clipped
    polygon retains at least `min_visible` of the ORIGINAL polygon area. The
    detector box is the AABB of that clipped polygon. Boxes with a normalized
    side below `MIN_BOX_SIDE_NORM` are dropped (too small to train on).
    """
    W, H = float(sample.width), float(sample.height)
    out: list[YoloBox] = []
    for ann in sample.annotations:
        poly = [(float(x), float(y)) for x, y in ann.polygon]
        orig_area = _polygon_area(poly)
        if orig_area <= 0:
            continue
        clipped = clip_polygon_to_rect(poly, W, H)
        if len(clipped) < 3:
            continue
        vis_area = _polygon_area(clipped)
        if vis_area / orig_area < min_visible:
            continue
        xs = [p[0] for p in clipped]
        ys = [p[1] for p in clipped]
        cx0, cy0, cx1, cy1 = min(xs), min(ys), max(xs), max(ys)
        cw, ch = cx1 - cx0, cy1 - cy0
        if cw <= 0 or ch <= 0:
            continue
        nxc = (cx0 + cx1) / 2 / W
        nyc = (cy0 + cy1) / 2 / H
        nw = cw / W
        nh = ch / H
        if nw < MIN_BOX_SIDE_NORM or nh < MIN_BOX_SIDE_NORM:
            continue
        out.append(YoloBox(ann.class_id, nxc, nyc, nw, nh))
    return out


def write_label_file(path: str, boxes: list[YoloBox]) -> None:
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(b.line() for b in boxes))
        if boxes:
            fh.write("\n")


def write_dataset_yaml(path: str, root: str) -> None:
    """Emit Ultralytics dataset.yaml for the v0 class set."""
    lines = [
        f"# docdet dataset ({CLASS_VERSION}) — generated by synthgen",
        f"path: {root}",
        "train: images/train",
        "val: images/val",
        "test: images/test",
        "",
        "names:",
    ]
    for i, name in enumerate(CLASS_NAMES):
        lines.append(f"  {i}: {name}")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")


def sample_manifest(sample: Sample, sample_id: str, boxes: list[YoloBox]) -> dict:
    """Build the per-sample provenance + ground-truth manifest entry."""
    from collections import Counter

    counts = Counter(CLASS_NAMES[b.class_id] for b in boxes)
    return {
        "sampleId": sample_id,
        "classVersion": CLASS_VERSION,
        "docCategory": sample.category,
        "templateFamilyId": sample.template_family,
        "templateVersionId": sample.template_version,
        "seed": sample.seed,
        "language": sample.language,
        "containsRealPersonalData": False,
        "width": sample.width,
        "height": sample.height,
        "qualityTags": sorted(set(sample.quality_tags)),
        "boxCount": len(boxes),
        "classCounts": dict(counts),
        "groundTruth": sample.ground_truth,
    }
